// Essence Crown: Shard Wars - Card Database
// Generated from official card data
// Total: 109 playable cards + 11 deities
// Last updated: 2025-12-02

const CARD_BACK_IMAGE = 'https://cdn1.sharemyimage.com/2025/12/02/Back.png';

const CARD_DATABASE = [
    {
        id: 'EC-003',
        name: 'Second Sun Vanguard',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 2,
        power: 3,
        toughness: 2,
        domain: 'Second Sun',
        effect: 'When Second Sun Vanguard attacks for the first time each turn, it deals +1 Essence damage to the defending Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/3.png'
    },
    {
        id: 'EC-004',
        name: 'Shardstorm Lancer',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 3,
        power: 4,
        toughness: 2,
        domain: 'New Earth',
        effect: 'On Play: Deal 1 Essence damage to target Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/4.png'
    },
    {
        id: 'EC-005',
        name: 'Gray Threshold Adept',
        type: 'Avatar',
        rarity: 'Shard',
        aspects: ['Gray'],
        cost: 1,
        power: 1,
        toughness: 2,
        domain: 'Threshold',
        effect: 'On Play: You gain +1 KL this turn. (KL gained this way can exceed your current KL but not your KL maximum.)',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/5.png'
    },
    {
        id: 'EC-006',
        name: 'Abyssal Crownfeeder',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Null Abyss',
        effect: 'Whenever Abyssal Crownfeeder deals Essence damage to a Deity, you gain 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/6.png'
    },
    {
        id: 'EC-007',
        name: 'New Earth Guardian',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 2,
        power: 2,
        toughness: 3,
        domain: 'New Earth',
        effect: 'Guardian (While this Avatar is on New Earth, your opponent must target it with their first attack each turn if able).',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/7.png'
    },
    {
        id: 'EC-008',
        name: 'Solar Street Saint',
        type: 'Avatar',
        rarity: 'Shard',
        aspects: ['Glow'],
        cost: 1,
        power: 2,
        toughness: 1,
        domain: 'Second Sun',
        effect: 'On Play: If you have attacked this game, gain 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/8.png'
    },
    {
        id: 'EC-009',
        name: 'Crownline Courier',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Crownline',
        effect: 'On Play: Look at the top 2 cards of your deck. Put 1 into your hand and the other on the bottom of your deck.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/9.png'
    },
    {
        id: 'EC-010',
        name: 'Radiant Shard Titan',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Glow'],
        cost: 5,
        power: 6,
        toughness: 5,
        domain: 'Second Sun',
        effect: 'On Play: Your other Glow Avatars gain +1 Power until end of turn. When Radiant Shard Titan attacks, it deals 1 Essence damage to the defending Deity before combat damage.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/10.png'
    },
    {
        id: 'EC-011',
        name: 'Shard Medics of Solara',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 2,
        power: 1,
        toughness: 3,
        domain: 'Solara',
        effect: 'On Play: Restore 2 Essence to your Deity. When Shard Medics of Solara leaves New Earth, restore 1 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/11.png'
    },
    {
        id: 'EC-012',
        name: 'Solar Flare Surge',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 2,
        domain: 'Second Sun',
        effect: 'Deal 3 Essence damage to target Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/12.png'
    },
    {
        id: 'EC-013',
        name: 'Crown Equilibrium',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 2,
        domain: 'Crown',
        effect: 'Both Deities gain 2 Essence. Draw a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/13.png'
    },
    {
        id: 'EC-014',
        name: 'Essence Rally',
        type: 'Spell',
        rarity: 'Shard',
        aspects: ['Glow'],
        cost: 1,
        domain: 'New Earth',
        effect: 'Up to two Glow Avatars you control get +1 Power until end of turn. If you attacked this turn, gain 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/14.png'
    },
    {
        id: 'EC-015',
        name: 'Second Sun Blessing',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 2,
        domain: 'Second Sun',
        effect: 'Restore 3 Essence to your Deity. If you control 3 or more Glow Avatars, instead restore 4 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/15.png'
    },
    {
        id: 'EC-016',
        name: 'Shardline Charge',
        type: 'Spell',
        rarity: 'Shard',
        aspects: ['Glow'],
        cost: 1,
        domain: 'New Earth',
        effect: 'Target Avatar gains +2 Power and "When this Avatar deals Essence damage to a Deity this turn, draw a card."',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/16.png'
    },
    {
        id: 'EC-017',
        name: 'New Earth Resync',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 2,
        domain: 'New Earth',
        effect: 'Choose one: • Restore 2 Essence to your Deity, then you gain +1 KL this turn. • Restore 1 Essence to each Deity and draw a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/17.png'
    },
    {
        id: 'EC-018',
        name: 'KL Ignition',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 1,
        domain: 'Crownline',
        effect: 'You gain +2 KL this turn. At end of turn, lose 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/18.png'
    },
    {
        id: 'EC-019',
        name: 'Crown’s Protection Protocol',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 2,
        domain: 'Crown',
        effect: 'Choose up to two Avatars you control. They gain “This Avatar cannot be destroyed by Spells this turn.”',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/19.png'
    },
    {
        id: 'EC-020',
        name: 'Solar Rewrite',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 3,
        domain: 'Second Sun / Nullgrid',
        effect: 'Look at the top 4 cards of your deck. You may reveal up to 2 Glow or Gray cards from among them and put them into your hand. Put the rest on the bottom of your deck in any order.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/20.png'
    },
    {
        id: 'EC-021',
        name: 'Nullblade Stalker',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 2,
        power: 2,
        toughness: 3,
        domain: 'Nullgrid',
        effect: 'Whenever Nullblade Stalker deals Essence damage to a Deity, that Deity’s controller loses 1 KL.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/21.png'
    },
    {
        id: 'EC-022',
        name: 'Grid Siphon Scribe',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 2,
        power: 1,
        toughness: 3,
        domain: 'Nullgrid',
        effect: 'On Play: Target opponent loses 1 KL. Whenever an opponent loses KL, Grid Siphon Scribe gets +1 Power until end of turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/22.png'
    },
    {
        id: 'EC-023',
        name: 'Shard Jailer of the Null',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 3,
        power: 2,
        toughness: 4,
        domain: 'Null Abyss',
        effect: 'On Play: Choose an Avatar an opponent controls with cost 2 or less. That Avatar cannot attack while Shard Jailer of the Null remains on New Earth.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/23.png'
    },
    {
        id: 'EC-024',
        name: 'Voidline Saboteur',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Nullgrid',
        effect: 'On Play: Look at the top card of target opponent’s deck. You may place it on the bottom of their deck.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/24.png'
    },
    {
        id: 'EC-025',
        name: 'Crown Auditor',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Crownline',
        effect: 'On Play: Look at the top 2 cards of your deck. You may reveal a Spell from among them and put it into your hand. Put the rest back in any order.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/25.png'
    },
    {
        id: 'EC-026',
        name: 'Obsidian Shard Colossus',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Void'],
        cost: 5,
        power: 5,
        toughness: 6,
        domain: 'Null Abyss',
        effect: 'On Play: Each opponent loses 2 Essence. Whenever Obsidian Shard Colossus attacks, you may drain 1 KL from the defending player.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/26.png'
    },
    {
        id: 'EC-027',
        name: 'Nullgrid Warden',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 2,
        power: 1,
        toughness: 4,
        domain: 'Nullgrid',
        effect: 'Guardian. Whenever Nullgrid Warden is dealt damage, its controller gains 1 KL.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/27.png'
    },
    {
        id: 'EC-028',
        name: 'Void Collapse',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 3,
        domain: 'Null Abyss',
        effect: 'Target opponent loses 2 Essence and 1 KL. If that opponent has 10 or less Essence, they lose an additional 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/28.png'
    },
    {
        id: 'EC-029',
        name: 'Grid Snuff',
        type: 'Spell',
        rarity: 'Shard',
        aspects: ['Void'],
        cost: 1,
        domain: 'Nullgrid',
        effect: 'Destroy target Avatar with cost 1 or less. If that Avatar was Glow, its controller loses 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/29.png'
    },
    {
        id: 'EC-030',
        name: 'Essence Leak',
        type: 'Spell',
        rarity: 'Shard',
        aspects: ['Void'],
        cost: 1,
        domain: 'Null Abyss',
        effect: 'Target opponent loses 2 Essence. You lose 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/30.png'
    },
    {
        id: 'EC-031',
        name: 'Null Directive',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 2,
        domain: 'Nullgrid',
        effect: 'Choose one: • Destroy target Avatar with cost 3 or less. • Target opponent discards a card at random.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/31.png'
    },
    {
        id: 'EC-032',
        name: 'Shard Confiscation',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 2,
        domain: 'Crownline / Nullgrid',
        effect: 'Look at target opponent’s hand. Choose a card with cost 3 or less. That player discards that card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/32.png'
    },
    {
        id: 'EC-033',
        name: 'KL Blackout',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 2,
        domain: 'Null Abyss',
        effect: 'Until your next turn, target opponent’s KL maximum is reduced by 2 (to a minimum of 1). Draw a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/33.png'
    },
    {
        id: 'EC-034',
        name: 'Grayscale Arbitration',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 3,
        domain: 'Gray Court',
        effect: 'Destroy target Avatar with cost 4 or more. Each Deity loses 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/34.png'
    },
    {
        id: 'EC-035',
        name: 'Crown Audit',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 1,
        domain: 'Crownline',
        effect: 'Look at the top 3 cards of your deck. Reveal a Void or Gray card from among them and put it into your hand. Put the rest on the bottom of your deck in any order.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/35.png'
    },
    {
        id: 'EC-042',
        name: 'Shardline Sprinter',
        type: 'Avatar',
        rarity: 'Shard',
        aspects: ['Glow'],
        cost: 1,
        power: 1,
        toughness: 2,
        domain: 'New Earth',
        effect: 'Shardline Sprinter gets +1 Power while you control another attacking Avatar.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/42.png'
    },
    {
        id: 'EC-043',
        name: 'Second Sun Skyspear',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Second Sun',
        effect: 'On Play: You may deal 1 damage to target Avatar. If that Avatar is destroyed this way, gain 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/43.png'
    },
    {
        id: 'EC-044',
        name: 'Crown Halo Escort',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow', 'Gray'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Crownline',
        effect: 'Guardian. When Crown Halo Escort enters New Earth, restore 1 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/44.png'
    },
    {
        id: 'EC-045',
        name: 'Solar Courier Knight',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 2,
        power: 3,
        toughness: 1,
        domain: 'Crownline / Logistics',
        effect: 'On Play: You may draw a card, then discard a card. Whenever Solar Courier Knight deals Essence damage to a Deity, you may scry 1 (look at the top card of your deck; you may put it on the bottom).',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/45.png'
    },
    {
        id: 'EC-046',
        name: 'Beacon of New Earth',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Glow'],
        cost: 4,
        power: 3,
        toughness: 5,
        domain: 'New Earth',
        effect: 'On Play: Restore 3 Essence to your Deity. While Beacon of New Earth is on New Earth, your other Avatars get +0/+1.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/46.png'
    },
    {
        id: 'EC-047',
        name: 'Twin-Sun Duelist',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Second Sun',
        effect: 'When Twin-Sun Duelist attacks, if you played a Spell this turn, it gains +1 Power until end of turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/47.png'
    },
    {
        id: 'EC-048',
        name: 'Streetlight Herald',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow', 'Gray'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Second Sun / Gray Court',
        effect: 'On Play: If you have fewer cards in hand than an opponent, draw a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/48.png'
    },
    {
        id: 'EC-049',
        name: 'Radiant Crown Beast',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Glow', 'Beast'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Pet Sanctuary',
        effect: 'On Play: If you control another Beast, restore 2 Essence to your Deity. Whenever Radiant Crown Beast attacks, you may give another attacking Beast +1 Power until end of turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/49.png'
    },
    {
        id: 'EC-050',
        name: 'Solara Gatekeeper',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Glow', 'Gray'],
        cost: 4,
        power: 4,
        toughness: 4,
        domain: 'Solara',
        effect: 'Guardian. On Play: You may destroy target Avatar with cost 2 or less.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/50.png'
    },
    {
        id: 'EC-051',
        name: 'Nullgrid Tracker',
        type: 'Avatar',
        rarity: 'Shard',
        aspects: ['Void'],
        cost: 1,
        power: 1,
        toughness: 2,
        domain: 'Nullgrid',
        effect: 'On Play: Look at the top card of your deck. You may put it on the bottom of your deck.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/51.png'
    },
    {
        id: 'EC-052',
        name: 'Shard Interrogator',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 3,
        power: 3,
        toughness: 2,
        domain: 'Null Abyss',
        effect: 'On Play: Target opponent reveals their hand. Choose a non-Avatar card from it. That player discards that card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/52.png'
    },
    {
        id: 'EC-053',
        name: 'Abyssal Archivist',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void', 'Gray'],
        cost: 3,
        power: 2,
        toughness: 3,
        domain: 'Null Abyss / Gray Court',
        effect: 'On Play: You may return a Spell card from your discard pile to your hand.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/53.png'
    },
    {
        id: 'EC-054',
        name: 'Crown Grid Warden',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 4,
        power: 3,
        toughness: 5,
        domain: 'Nullgrid / Crownline',
        effect: 'Guardian. Whenever an opponent draws their second card in a single turn, they lose 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/54.png'
    },
    {
        id: 'EC-055',
        name: 'Shardbreaker Inquisitor',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 3,
        power: 4,
        toughness: 2,
        domain: 'Null Abyss',
        effect: 'Whenever Shardbreaker Inquisitor destroys an Avatar, that Avatar’s controller loses 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/55.png'
    },
    {
        id: 'EC-056',
        name: 'Void Courier Shade',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 2,
        power: 1,
        toughness: 3,
        domain: 'Logistics / Nullgrid',
        effect: 'On Play: You may move 1 Essence from your Deity to target opponent’s Deity. Whenever you lose Essence outside of combat, Void Courier Shade gets +1 Power until end of turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/56.png'
    },
    {
        id: 'EC-057',
        name: 'Null Rift Hound',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void', 'Beast'],
        cost: 2,
        power: 3,
        toughness: 1,
        domain: 'Sanctuary Void',
        effect: 'When Null Rift Hound enters New Earth, target opponent loses 1 Essence. When Null Rift Hound dies, you may drain 1 KL from target opponent.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/57.png'
    },
    {
        id: 'EC-058',
        name: 'Shardline Reaper',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 4,
        power: 4,
        toughness: 3,
        domain: 'Null Abyss',
        effect: 'On Play: Destroy target Avatar with cost 2 or less. Whenever Shardline Reaper attacks, each player loses 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/58.png'
    },
    {
        id: 'EC-059',
        name: 'Gridlock Titan',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Void', 'Gray'],
        cost: 6,
        power: 6,
        toughness: 7,
        domain: 'Nullgrid / Gray Court',
        effect: 'On Play: Until your next turn, opponents cannot gain KL above their starting KL. Whenever an opponent spends KL, they lose 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/59.png'
    },
    {
        id: 'EC-060',
        name: 'Crown Ledger Keeper',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 2,
        power: 1,
        toughness: 3,
        domain: 'Crownline',
        effect: 'On Play: Draw a card, then discard a card. Whenever you discard a card, you may gain 1 KL this turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/60.png'
    },
    {
        id: 'EC-061',
        name: 'Gray Court Mediator',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 3,
        power: 2,
        toughness: 4,
        domain: 'Gray Court',
        effect: 'On Play: Each player restores 1 Essence. Whenever a Spell is played, you may have each Deity lose 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/61.png'
    },
    {
        id: 'EC-062',
        name: 'Shard Statistician',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Crownline',
        effect: 'On Play: Look at the top 3 cards of your deck. You may reveal an Avatar from among them and put it into your hand. Put the rest back on top in any order.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/62.png'
    },
    {
        id: 'EC-063',
        name: 'Pet Sanctuary Caretaker',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray', 'Beast'],
        cost: 2,
        power: 1,
        toughness: 3,
        domain: 'Pet Sanctuary',
        effect: 'On Play: Restore 1 Essence to each Deity. Whenever a Beast you control dies, you may restore 1 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/63.png'
    },
    {
        id: 'EC-064',
        name: 'Grayline Arbiter',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 4,
        power: 3,
        toughness: 4,
        domain: 'Gray Court',
        effect: 'On Play: Choose an Avatar. Its Power becomes 2 and its Toughness becomes 2 until Grayline Arbiter leaves New Earth.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/64.png'
    },
    {
        id: 'EC-065',
        name: 'Crown Data Analyst',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 3,
        power: 1,
        toughness: 4,
        domain: 'Crownline',
        effect: 'On Play: Look at the top 5 cards of your deck. You may reveal up to 2 non-Avatar cards from among them and put them into your hand. Put the rest on the bottom of your deck in any order.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/65.png'
    },
    {
        id: 'EC-066',
        name: 'Logistics Coordinator',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Logistics',
        effect: 'On Play: You may move 1 Essence from one Deity to another (you choose the source and recipient).',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/66.png'
    },
    {
        id: 'EC-067',
        name: 'Gray Shard Sentinel',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Gray Court',
        effect: 'Guardian. Whenever Gray Shard Sentinel blocks, you may draw a card, then discard a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/67.png'
    },
    {
        id: 'EC-068',
        name: 'Crown Equilibrium Adept',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 3,
        power: 2,
        toughness: 3,
        domain: 'Crownline',
        effect: 'On Play: If your Deity has more Essence than an opponent’s Deity, you lose 2 Essence and draw 2 cards. Otherwise, restore 2 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/68.png'
    },
    {
        id: 'EC-072',
        name: 'Kaixu’s Shardborne Avatar',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Glow', 'Void'],
        cost: 4,
        power: 4,
        toughness: 4,
        domain: 'Shattered Sun',
        effect: 'On Play: If your Deity is Demon Lord Kaixu, Crownshatter Sovereign, you may play this card for 3 KL instead. Whenever you play your second card in a turn, Kaixu’s Shardborne Avatar gets +2 Power until end of turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/72.png'
    },
    {
        id: 'EC-073',
        name: 'Parallel Self of Kaixu',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Glow', 'Void', 'Gray'],
        cost: 5,
        power: 3,
        toughness: 5,
        domain: 'Shattered Sun',
        effect: 'On Play: Copy the Passive ability of your Deity until end of turn. (It triggers as though this Avatar were your Deity.) Whenever you activate a God Code, Parallel Self of Kaixu gains +3 Power and cannot be destroyed this turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/73.png'
    },
    {
        id: 'EC-074',
        name: 'Crownshatter Executioner',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Crownline / Null Abyss',
        effect: 'Whenever you choose one or more modes or choices for a card’s effect, an opponent loses 1 Essence. On Play: If your Deity is Demon Lord Kaixu, Crownshatter Sovereign, destroy target Avatar with cost 3 or less.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/74.png'
    },
    {
        id: 'EC-075',
        name: 'Kaixu’s Edict: Board Reset',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Gray', 'Void'],
        cost: 5,
        domain: 'Shattered Sun',
        effect: 'Destroy all Avatars. Each Deity loses 3 Essence. If your Deity is Demon Lord Kaixu, Crownshatter Sovereign, instead each opponent loses 5 Essence and you may keep one Avatar you control.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/75.png'
    },
    {
        id: 'EC-076',
        name: 'Shattered Sun Cataclysm',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Glow', 'Void', 'Gray'],
        cost: 6,
        domain: 'Shattered Sun',
        effect: 'Each opponent sacrifices two Avatars, then loses 3 KL. Your Avatars gain +2 Power until end of turn. If your Deity is Demon Lord Kaixu, Crownshatter Sovereign, draw 2 cards.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/76.png'
    },
    {
        id: 'EC-077',
        name: 'Estifar’s Voidwing Alpha',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Void', 'Beast'],
        cost: 4,
        power: 4,
        toughness: 3,
        domain: 'Sanctuary Void',
        effect: 'On Play: Create a 2/2 Void Beast Avatar token. Beasts you control have “When this Avatar dies, target opponent loses 1 Essence.” If your Deity is Estifar, Voidwing Regent, your first Beast each turn costs 1 less KL to play.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/77.png'
    },
    {
        id: 'EC-078',
        name: 'Moonpack Howler',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void', 'Beast'],
        cost: 2,
        power: 2,
        toughness: 2,
        domain: 'Sanctuary Void',
        effect: 'Whenever another Beast enters New Earth under your control, Moonpack Howler gets +1 Power until end of turn. If your Deity is Estifar, Voidwing Regent, it also restores 1 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/78.png'
    },
    {
        id: 'EC-079',
        name: 'Sanctuary Packmother',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Void', 'Gray', 'Beast'],
        cost: 5,
        power: 3,
        toughness: 5,
        domain: 'Sanctuary Void',
        effect: 'On Play: Create two 2/2 Void Beast Avatar tokens. At the beginning of your end step, if three or more Beasts died this turn, restore 3 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/79.png'
    },
    {
        id: 'EC-080',
        name: 'Estifar’s Call: Pack Ascension',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Void', 'Gray'],
        cost: 4,
        domain: 'Sanctuary Void',
        effect: 'Create two 3/3 Void Beast Avatar tokens with Guardian. If your Deity is Estifar, Voidwing Regent, your Beasts get +1 Power and “When this Avatar dies, draw a card” until end of turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/80.png'
    },
    {
        id: 'EC-081',
        name: 'Voidwing Stampede',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 3,
        domain: 'Sanctuary Void',
        effect: 'Beasts you control get +2 Power until end of turn. Each Beast that deals Essence damage to a Deity this turn causes that Deity’s controller to lose 1 KL.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/1-1.png'
    },
    {
        id: 'EC-082',
        name: 'Lokaya’s Stillpoint Avatar',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Gray', 'Glow'],
        cost: 4,
        power: 2,
        toughness: 5,
        domain: 'Gray Court / New Earth',
        effect: 'On Play: Tap up to two Avatars you don’t control. They do not untap during their controller’s next untap step. At the end of your turn, if no Avatar you control attacked this turn, restore 1 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/2-1.png'
    },
    {
        id: 'EC-083',
        name: 'Silent Crown Arbiter',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Gray'],
        cost: 5,
        power: 3,
        toughness: 6,
        domain: 'Gray Court',
        effect: 'On Play: Choose up to two Spells. They cannot be played until your next turn. As long as Silent Crown Arbiter is on New Earth, players can play only one Spell per turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/3-1.png'
    },
    {
        id: 'EC-084',
        name: 'New Earth Monk of Stillness',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Glow', 'Gray'],
        cost: 2,
        power: 1,
        toughness: 4,
        domain: 'New Earth',
        effect: 'Guardian. At the end of your turn, if no Avatar you control attacked this turn, you may draw a card, then discard a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/4-1.png'
    },
    {
        id: 'EC-085',
        name: 'Lokaya’s Edict: Be Still',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Gray'],
        cost: 3,
        domain: 'Gray Court',
        effect: 'Tap up to three Avatars you don’t control. Those Avatars cannot attack during their controller’s next turn. If your Deity is Lokaya, Crown of Stillness, restore 3 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/5-1.png'
    },
    {
        id: 'EC-086',
        name: 'Crown of Quiet Worlds',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Gray', 'Glow'],
        cost: 4,
        domain: 'Gray Court / New Earth',
        effect: 'Until your next turn, players cannot declare more than one attack per turn. If no Avatar you control attacks this turn, at the beginning of your next turn draw 2 cards and restore 2 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/6-1.png'
    },
    {
        id: 'EC-087',
        name: 'Second Sun Street Brawler',
        type: 'Avatar',
        rarity: 'Shard',
        aspects: ['Glow'],
        cost: 2,
        power: 3,
        toughness: 1,
        domain: 'Second Sun',
        effect: 'Whenever Second Sun Street Brawler deals Essence damage to a Deity, you gain +1 KL this turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/7-1.png'
    },
    {
        id: 'EC-088',
        name: 'New Earth Rally Captain',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Glow'],
        cost: 3,
        power: 2,
        toughness: 4,
        domain: 'New Earth',
        effect: 'On Play: Until end of turn, Avatars you control get +1 Power. Whenever three or more Avatars you control attack in the same turn, restore 2 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/8-1.png'
    },
    {
        id: 'EC-089',
        name: 'Solara Crown Paladin',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Glow', 'Gray'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Solara / Crownline',
        effect: 'Guardian. While Solara Crown Paladin is on New Earth, damage that would reduce your Deity’s Essence to 0 reduces it to 1 instead (once per game).',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/9-1.png'
    },
    {
        id: 'EC-090',
        name: 'Sanctuary Sunpride',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Glow', 'Beast'],
        cost: 4,
        power: 4,
        toughness: 4,
        domain: 'Pet Sanctuary',
        effect: 'On Play: Restore 2 Essence to your Deity. Beasts you control get +1 Power while attacking Deities.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/10-1.png'
    },
    {
        id: 'EC-091',
        name: 'Second Sun Charge Line',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Glow'],
        cost: 2,
        domain: 'Second Sun',
        effect: 'Up to two target Avatars you control get +2 Power until end of turn. If both attack this turn, draw a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/11-1.png'
    },
    {
        id: 'EC-092',
        name: 'Essence Crown Strike',
        type: 'Spell',
        rarity: 'Shard',
        aspects: ['Glow'],
        cost: 1,
        domain: 'Crownline / Second Sun',
        effect: 'Deal 2 Essence damage to target Deity or Avatar. If you target a Deity, you lose 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/12-1.png'
    },
    {
        id: 'EC-093',
        name: 'New Earth Reprieve',
        type: 'Spell',
        rarity: 'Shard',
        aspects: ['Glow', 'Gray'],
        cost: 1,
        domain: 'New Earth / Gray Court',
        effect: 'Restore 2 Essence to your Deity. If an opponent has more Essence than you, restore 3 Essence instead.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/13-1.png'
    },
    {
        id: 'EC-094',
        name: 'Solar Uprising',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Glow'],
        cost: 4,
        domain: 'Second Sun / New Earth',
        effect: 'Until end of turn, Avatars you control get +1 Power and “Whenever this Avatar deals Essence damage to a Deity this turn, that Deity loses 1 additional Essence.”',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/14-1.png'
    },
    {
        id: 'EC-095',
        name: 'Null Alley Cutthroat',
        type: 'Avatar',
        rarity: 'Shard',
        aspects: ['Void'],
        cost: 2,
        power: 2,
        toughness: 1,
        domain: 'Nullgrid',
        effect: 'Whenever Null Alley Cutthroat attacks and isn’t blocked, target opponent loses 1 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/15-1.png'
    },
    {
        id: 'EC-096',
        name: 'Abyss Courier Hunter',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Null Abyss / Logistics',
        effect: 'On Play: Target opponent discards a card. If they cannot, they lose 2 Essence instead.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/16-1.png'
    },
    {
        id: 'EC-097',
        name: 'Shard Debt Collector',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void', 'Gray'],
        cost: 4,
        power: 3,
        toughness: 4,
        domain: 'Nullgrid / Crownline',
        effect: 'On Play: Target opponent loses 1 Essence for each card in your discard pile, up to 3. Whenever an opponent discards a card, restore 1 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/17-1.png'
    },
    {
        id: 'EC-098',
        name: 'Abyssal Faultline Mage',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 4,
        power: 3,
        toughness: 4,
        domain: 'Null Abyss',
        effect: 'On Play: Choose one — • Destroy target Avatar with cost 3 or less. • Each opponent discards a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/18-1.png'
    },
    {
        id: 'EC-099',
        name: 'Void Ledger Wipe',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Void', 'Gray'],
        cost: 3,
        domain: 'Null Abyss / Gray Court',
        effect: 'Each player discards two cards. Then you may return a Void or Gray card from your discard pile to your hand.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/19-1.png'
    },
    {
        id: 'EC-100',
        name: 'Essence Ransom',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Void'],
        cost: 2,
        domain: 'Nullgrid',
        effect: 'Target opponent chooses one — • They lose 3 Essence. • They lose 1 KL and you draw 2 cards.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/20-1.png'
    },
    {
        id: 'EC-101',
        name: 'Nullgrid Surge',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 1,
        domain: 'Nullgrid',
        effect: 'Target opponent loses 1 Essence and 1 KL. If they have 10 or less Essence, they lose 1 additional Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/21-1.png'
    },
    {
        id: 'EC-102',
        name: 'Abyssal Echoes',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Void'],
        cost: 2,
        domain: 'Null Abyss',
        effect: 'Return up to one Void Avatar and up to one Void Spell from your discard pile to your hand. Then lose 2 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/22-1.png'
    },
    {
        id: 'EC-103',
        name: 'Equity Scribe of Crownline',
        type: 'Avatar',
        rarity: 'Shard',
        aspects: ['Gray'],
        cost: 2,
        power: 1,
        toughness: 3,
        domain: 'Crownline',
        effect: 'On Play: If you have fewer cards in hand than an opponent, draw a card. Otherwise, discard a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/23-1.png'
    },
    {
        id: 'EC-104',
        name: 'Balancebreaker Advocate',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 3,
        power: 2,
        toughness: 3,
        domain: 'Gray Court',
        effect: 'On Play: The player with the highest Essence loses 2 Essence and the player with the lowest Essence gains 2 Essence. (You choose in ties.)',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/24-1.png'
    },
    {
        id: 'EC-105',
        name: 'Crownline Negotiator',
        type: 'Avatar',
        rarity: 'Adept',
        aspects: ['Gray'],
        cost: 3,
        power: 2,
        toughness: 4,
        domain: 'Crownline',
        effect: 'Whenever an opponent loses Essence during your turn, you may gain 1 KL this turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/25-1.png'
    },
    {
        id: 'EC-106',
        name: 'Gray Court Archivist',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 4,
        power: 2,
        toughness: 5,
        domain: 'Gray Court',
        effect: 'On Play: Look at the top 4 cards of your deck. You may reveal up to 2 Gray cards from among them and put them into your hand. Put the rest on the bottom of your deck in any order.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/26-1.png'
    },
    {
        id: 'EC-107',
        name: 'Gray Court Injunction',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Gray'],
        cost: 2,
        domain: 'Gray Court',
        effect: 'Choose Avatar or Spell. Until your next turn, each player can play only one card of the chosen type each turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/27-1.png'
    },
    {
        id: 'EC-108',
        name: 'Scales of New Earth',
        type: 'Spell',
        rarity: 'Adept',
        aspects: ['Gray', 'Glow'],
        cost: 3,
        domain: 'New Earth / Gray Court',
        effect: 'Each player may restore up to 3 Essence to their Deity. For each opponent who does, draw a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/28-1.png'
    },
    {
        id: 'EC-109',
        name: 'Crownline Reallocator',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Gray', 'Void'],
        cost: 2,
        domain: 'Crownline / Nullgrid',
        effect: 'Move up to 3 Essence among Deities as you choose.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/29-1.png'
    },
    {
        id: 'EC-110',
        name: 'Shard of Probabilities',
        type: 'Spell',
        rarity: 'Shard',
        aspects: ['Gray'],
        cost: 1,
        domain: 'Gray Court',
        effect: 'Look at the top 2 cards of your deck. Put one into your hand and the other on the bottom of your deck.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/30-1.png'
    },
    {
        id: 'EC-111',
        name: 'Shard War Envoy',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Glow', 'Void'],
        cost: 3,
        power: 3,
        toughness: 3,
        domain: 'Shattered Sun',
        effect: 'On Play: Each player loses 1 Essence. Whenever you play both a Glow card and a Void card in the same turn, Shard War Envoy gets +2 Power until end of turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/31-1.png'
    },
    {
        id: 'EC-112',
        name: 'Null-Crown Diplomat',
        type: 'Avatar',
        rarity: 'Master',
        aspects: ['Void', 'Gray'],
        cost: 3,
        power: 2,
        toughness: 4,
        domain: 'Nullgrid / Crownline',
        effect: 'On Play: Target opponent discards a card unless they choose to restore 2 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/32-1.png'
    },
    {
        id: 'EC-113',
        name: 'Radiant Equilibrium Sage',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Glow', 'Gray'],
        cost: 4,
        power: 3,
        toughness: 4,
        domain: 'Second Sun / Gray Court',
        effect: 'On Play: Set each Deity’s Essence to the average (rounded down) of all Deities’ Essence values. Whenever your Deity gains Essence, you may draw a card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/33-1.png'
    },
    {
        id: 'EC-114',
        name: 'Shattered Triune Avatar',
        type: 'Avatar',
        rarity: 'Mythic',
        aspects: ['Glow', 'Void', 'Gray'],
        cost: 5,
        power: 4,
        toughness: 4,
        domain: 'Shattered Sun',
        effect: 'On Play: Choose one — • Draw 2 cards. • Target opponent discards 2 cards. • Restore 4 Essence to your Deity. Whenever you play your third card in a turn, you may choose one of these modes that hasn’t been chosen this game.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/34-1.png'
    },
    {
        id: 'EC-115',
        name: 'God Code Catalyst',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Glow', 'Void', 'Gray'],
        cost: 3,
        domain: 'Crownline / Shattered Sun',
        effect: 'Until end of turn, whenever you gain KL, you gain that much +1 instead. If your KL would go above 13 this turn and you have not activated your Deity’s God Code yet, you may activate it as though its condition were met.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/35-1.png'
    },
    {
        id: 'EC-116',
        name: 'Crown Synchrony Protocol',
        type: 'Spell',
        rarity: 'Master',
        aspects: ['Glow', 'Gray'],
        cost: 2,
        domain: 'Crownline / New Earth',
        effect: 'Choose up to two Avatars you control. Until end of turn, whenever one of them deals Essence damage to a Deity, restore 1 Essence to your Deity and that Avatar gets +1 Power.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/36-1.png'
    },
    {
        id: 'EC-117',
        name: 'Relic of the Second Sun',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Glow'],
        cost: 3,
        domain: 'Second Sun',
        effect: 'Until end of turn, whenever you play a Glow card, draw a card, then discard a card. If your Deity is Demon Lord Kaixu, Crownshatter Sovereign or Shattered Sun Chronicler, Glow Avatars you control also get +1 Power this turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/37-1.png'
    },
    {
        id: 'EC-118',
        name: 'Relic of the Voidwing',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Void'],
        cost: 3,
        domain: 'Sanctuary Void / Null Abyss',
        effect: 'Until end of turn, whenever a Beast you control dies, target opponent loses 1 Essence and you gain +1 KL this turn.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/38-1.png'
    },
    {
        id: 'EC-119',
        name: 'Relic of Still Waters',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Gray'],
        cost: 3,
        domain: 'Gray Court / New Earth',
        effect: 'Until your next turn, whenever an opponent declares an attack with exactly one Avatar, tap that Avatar and it does not attack. Restore 1 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/39-1.png'
    },
    {
        id: 'EC-120',
        name: 'Crown of Shard Unity',
        type: 'Spell',
        rarity: 'Mythic',
        aspects: ['Glow', 'Void', 'Gray'],
        cost: 4,
        domain: 'Crownline / Shattered Sun',
        effect: 'Choose up to three Avatars you control. They become Glow, Void, and Gray in addition to their other aspects until end of turn and get +1 Power. Draw a card for each different aspect among Avatars you control (maximum 3).',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/40-1.png'
    },
];

const DEITY_DATABASE = [
    {
        id: 'EC-001',
        name: 'Second Sun Herald',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Glow', 'Gray'],
        essence: 23,
        startingKL: 3,
        domain: 'Second Sun',
        effect: 'Passive – Solar Flow: At the start of your turn, if you control at least one Glow Avatar, gain +1 KL this turn. God Code – Crown of the Second Sun (once per game): When your KL would go above 13, instead set it to 13 and your Avatars gain +2 Power until end of turn. Target opponent loses 4 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/1.png'
    },
    {
        id: 'EC-002',
        name: 'Null Regent',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Void', 'Gray'],
        essence: 23,
        startingKL: 3,
        domain: 'Nullgrid',
        effect: 'Passive – Grid Drain: Whenever an enemy Avatar is destroyed, you may drain 1 KL from that Avatar’s controller. God Code – Crown of Absolute Zero (once per game): When your KL would go above 13, instead set it to 13 and target opponent loses 3 KL and 3 Essence. Then you may destroy up to one Avatar they control with cost 3 or less.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/2.png'
    },
    {
        id: 'EC-036',
        name: 'Crown Arbiter of Gray',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Gray'],
        essence: 24,
        startingKL: 3,
        domain: 'Gray Court',
        effect: 'Passive – Perfect Balance: At the end of each turn, if both Deities have the same Essence, you may draw a card. God Code – Final Arbitration (once per game): When your KL would go above 13, instead set it to 13 and activate this. Set each Deity’s Essence to the lower of the two values, then you gain 3 Essence.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/36.png'
    },
    {
        id: 'EC-037',
        name: 'Solar Beast Warden',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Glow', 'Beast'],
        essence: 22,
        startingKL: 3,
        domain: 'Pet Sanctuary / New Earth',
        effect: 'Passive – Packbond: Whenever a Beast Avatar enters New Earth under your control, restore 1 Essence to your Deity. God Code – Call of the Crown Pride (once per game): Create up to three 2/2 Glow Beast Avatars with Guardian on New Earth. Restore 3 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/37.png'
    },
    {
        id: 'EC-038',
        name: 'Zero Gear Conductor',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Gray', 'Void'],
        essence: 23,
        startingKL: 3,
        domain: 'Zero Gear / Logistics',
        effect: 'Passive – Calibrated Flow: Whenever you spend exactly all of your remaining KL to play a card, draw a card. God Code – Absolute Schedule Lock (once per game): Target opponent’s next turn, they cannot gain KL above their starting KL that turn and cannot draw more than 1 card.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/38.png'
    },
    {
        id: 'EC-039',
        name: 'Executive Aura Regent',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Glow', 'Gray'],
        essence: 21,
        startingKL: 4,
        domain: 'Executive Crown',
        effect: 'Passive – Presence of Wealth: Once per turn, when you play a Spell, you may gain 1 Essence. God Code – Golden Aura Cascade (once per game): Your Avatars gain +1 Power and “When this Avatar deals Essence damage to a Deity this turn, restore 1 Essence to your Deity.”',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/39.png'
    },
    {
        id: 'EC-040',
        name: 'Shattered Sun Chronicler',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Glow', 'Void', 'Gray'],
        essence: 20,
        startingKL: 3,
        domain: 'Shattered Sun',
        effect: 'Passive – Story of the Shards: Once per turn, when you play your second card that turn, draw a card. God Code – Canon Rewrite (once per game): Exile your hand. Draw 5 cards. Until end of turn, your Spells cost 1 less KL (minimum 0).',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/40.png'
    },
    {
        id: 'EC-041',
        name: 'Crown of the Pet Void',
        type: 'Deity',
        rarity: 'Mythic',
        aspects: ['Void', 'Beast'],
        essence: 22,
        startingKL: 3,
        domain: 'Sanctuary Void',
        effect: 'Passive – Dark Bond: Whenever a Beast Avatar you control dies, target opponent loses 1 Essence. God Code – Sanctuary Eclipse (once per game): Destroy up to two non-Beast Avatars. For each Avatar destroyed this way, you may create a 3/3 Void Beast Avatar.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/41.png'
    },
    {
        id: 'EC-069',
        name: 'Demon Lord Kaixu, Crownshatter Sovereign',
        type: 'Deity',
        rarity: 'Arcane',
        aspects: ['Glow', 'Void', 'Gray'],
        essence: 22,
        startingKL: 3,
        domain: 'Shattered Sun / Crownline',
        effect: 'Passive – Shard War Architect: Once per turn, when you play your second card that turn, choose two: • Each opponent loses 1 Essence. • You gain +1 KL this turn. • Draw a card. • Target Avatar you control gets +2 Power until end of turn. God Code – Final Shardstorm (once per game): When your KL would go above 13, instead set it to 13 and activate this. Each opponent sacrifices two Avatars if able. Each opponent loses 4 Essence. Until end of turn, your Avatars get +2 Power and “When this Avatar deals Essence damage to a Deity, that Deity loses that much Essence again.”',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/69.png'
    },
    {
        id: 'EC-070',
        name: 'Estifar, Voidwing Regent',
        type: 'Deity',
        rarity: 'Arcane',
        aspects: ['Void', 'Beast', 'Gray'],
        essence: 23,
        startingKL: 3,
        domain: 'Sanctuary Void / Null Abyss',
        effect: 'Passive – Familiar Swarm: The first time each turn that a Beast or a card with cost 2 or less enters New Earth under your control, you may have each opponent lose 1 Essence and you gain +1 KL this turn. God Code – Pack of the Shattered Moon (once per game): When your KL would go above 13, instead set it to 13 and activate this effect. Create four 2/2 Void Beast Avatars with “When this Avatar dies, target opponent loses 1 Essence.” Your Beasts gain +1 Power and Guardian until end of turn. Restore 3 Essence to your Deity.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/70.png'
    },
    {
        id: 'EC-071',
        name: 'Lokaya, Crown of Stillness',
        type: 'Deity',
        rarity: 'Arcane',
        aspects: ['Gray', 'Glow'],
        essence: 25,
        startingKL: 3,
        domain: 'Gray Court / New Earth',
        effect: 'Passive – Quiet Orbit: At the end of your turn, if no Avatar you control attacked this turn, you may restore 2 Essence to your Deity, then you may draw a card and discard a card. God Code – Stillpoint Rewrite (once per game): When your KL would go above 13, instead set it to 13 and activate this effect. Tap all Avatars you don’t control. Those Avatars cannot attack during their controller’s next turn. You restore 5 Essence and draw 3 cards.',
        image: 'https://cdn1.sharemyimage.com/2025/12/02/71.png'
    },
];

// Create combined ALL_CARDS array with normalized properties
// Cards use power/toughness but game engine expects attack/health
const ALL_CARDS = [...CARD_DATABASE, ...DEITY_DATABASE].map(card => ({
    ...card,
    // Normalize Avatar stats: power -> attack, toughness -> health
    attack: card.attack ?? card.power ?? 0,
    health: card.health ?? card.toughness ?? card.essence ?? 0
}));

// Helper function to get all deities
function getDeities() {
    return DEITY_DATABASE;
}

// Helper function to get all non-deity cards
function getPlayableCards() {
    return CARD_DATABASE;
}

// Helper function to find a card by ID
function getCardById(id) {
    return ALL_CARDS.find(c => c.id === id);
}

// Export for use in game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CARD_DATABASE, DEITY_DATABASE, CARD_BACK_IMAGE, ALL_CARDS, getDeities, getPlayableCards, getCardById };
}
